"""Added progress column with default 'Not Yet Started'

Revision ID: 322e567e216d
Revises: 5074c8f6365a
Create Date: 2025-03-26 11:19:33.794165

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '322e567e216d'
down_revision = '5074c8f6365a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('progress', sa.Enum('Not Yet Started', 'On Hold', 'In Progress', 'Completed', 'Canceled', name='progress_status'), nullable=False, server_default="Not Yet Started"))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('progress')

    # ### end Alembic commands ###
