"""add subcon fk

Revision ID: 3f0a63e2bf25
Revises: 7559ea36253e
Create Date: 2025-04-01 21:31:13.770329

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3f0a63e2bf25'
down_revision = '7559ea36253e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcontractor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('user_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('fk_subcon', 'user', ['user_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('subcontractor', schema=None) as batch_op:
        batch_op.drop_constraint('fk_subcon', type_='foreignkey')
        batch_op.drop_column('user_id')

    # ### end Alembic commands ###
