"""Add is_read column to Message model

Revision ID: 499d0f9d6d37
Revises: 2c6bb178a977
Create Date: 2025-04-05 18:30:18.754203

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '499d0f9d6d37'
down_revision = '2c6bb178a977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_read', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('message', schema=None) as batch_op:
        batch_op.drop_column('is_read')

    # ### end Alembic commands ###
