"""Changed project_name column length to 70

Revision ID: 6656517d0aeb
Revises: 7bf2e046ccf7
Create Date: 2025-03-25 14:18:49.193283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6656517d0aeb'
down_revision = '7bf2e046ccf7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('project_name',
               existing_type=sa.VARCHAR(length=10000),
               type_=sa.String(length=70),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.alter_column('project_name',
               existing_type=sa.String(length=70),
               type_=sa.VARCHAR(length=10000),
               existing_nullable=True)

    # ### end Alembic commands ###
