"""Added address field to project

Revision ID: 7559ea36253e
Revises: 1bef56bdf97b
Create Date: 2025-04-01 16:27:19.420015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7559ea36253e'
down_revision = '1bef56bdf97b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('address', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('address')

    # ### end Alembic commands ###
