"""Renamed data column to project_name

Revision ID: 7bf2e046ccf7
Revises: d33955badc52
Create Date: 2025-03-25 13:39:39.973961
"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '7bf2e046ccf7'
down_revision = 'd33955badc52'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        # Migrate the data from 'data' to 'project_name'
        op.execute('UPDATE project SET project_name = data') # ADDED BY CHATGPT FOR FUTURE REFERENCE
        
        # Add the 'project_name' column and drop the 'data' column
        batch_op.add_column(sa.Column('project_name', sa.String(length=10000), nullable=True))
        batch_op.drop_column('data')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        # Add the 'data' column and drop the 'project_name' column
        batch_op.add_column(sa.Column('data', sa.VARCHAR(length=10000), nullable=True))
        batch_op.drop_column('project_name')

    # ### end Alembic commands ###
