"""Renamed data column to project_name

Revision ID: 9933290e64dd
Revises: 499d0f9d6d37
Create Date: 2025-04-08 21:43:53.216875

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9933290e64dd'
down_revision = '499d0f9d6d37'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('subcontractor_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(
            'fk_tasks_subcontractor_id',  # Explicitly name the foreign key
            'subcontractor',  # Ensure this matches the table name
            ['subcontractor_id'],
            ['id']
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_constraint('fk_tasks_subcontractor_id', type_='foreignkey')
        batch_op.drop_column('subcontractor_id')

    # ### end Alembic commands ###
